### ISSUE TITLE
font subfamily support

### ISSUE THREAD

**Issue by tommychat** [MuTsunTsai/fontfreeze#3] opened 2022-11-04 12:33 UTC
Hello,

I used the tool to generate a full set of variations and it worked as expected, except for the subfamily and/or style setting.

For instance I'm unable to set the following subfamilies:

 * light
 * retina
 * medium

**Comment by MuTsunTsai** [comment] 2022-11-06 11:35
TrueType specification suggests that the subfamily name should be one of the four basic styles (regular, italic, bold, and bold italic), and for other weight (e.g. light) the subfamily name should simply be regular. Refer to Code 2 of:

https://learn.microsoft.com/en-us/typography/opentype/spec/name#name-ids

I could, however, use Code 17 for those extended subfamily names you mentioned, technically called typographic subfamily name, and add a new input field for it. How about that?

**Comment by tommychat** [comment] 2022-11-08 11:33
I don't have enough knowledge in this domain to answer. However, I'm willing to test the change and share my report.

I listed the font with the `fc-list` command and indeed, the `style` field only contains `Regular` or `Bold`.

```
% fc-list | grep Fira | grep Tommy                                                                                                           FiraCode-Retina_Tommy.ttf: Fira Code Tommy:style=Regular
FiraCode-Light_Tommy.ttf: Fira Code Tommy:style=Regular
FiraCode-Medium_Tommy.ttf: Fira Code Tommy:style=Regular
iraCode-Bold_Tommy.ttf: Fira Code Tommy:style=Bold
```

Would the change you propose fill the `style` field with the appropriate the values, like with the default font where we can see that non-basic families are set?

```
% fc-list | grep "Fira.*Nerd"
Fira Code Retina Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=Retina,Regular
Fira Code Medium Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=Medium,Regular
Fira Code Light Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=Light,Regular
Fira Code SemiBold Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=SemiBold,Regular
Fira Code Regular Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=Regular
Fira Code Bold Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=Bold
```

**Comment by MuTsunTsai** [comment] 2022-11-09 08:59
Yes it will in this case. I just examine `Fira Code SemiBold Nerd Font Complete Mono.ttf` and sure enough, it assigns `SemiBold` exactly on Code 17 as expected. I've added the feature just now; see if it works for you.

**Comment by MuTsunTsai** [comment] 2023-03-08 07:36
I will assume the issue is fixed and close it. Feel free to reopen it if needed.

**Closed by MuTsunTsai** 2023-03-08 07:36 UTC
